model_name: LSTM

epochs: 5

batch_size: 64

learning_rate: 0.001

validation_split: 0.2

optimizer: adam

loss: binary_crossentropy

metrics:
  - accuracy

vocabulary_size: 10000

embedding_dim: 128

max_sequence_length: 200

lstm_units: 64